export enum Grade {
  "AAA+" = "AAA+",
  "AAA" = "AAA",
  "AA+" = "AA+",
  "AA" = "AA",
  "AA-" = "AA-",
  "A+" = "A+",
  "A" = "A",
  "A-" = "A-",
  "B+" = "B+",
  "B" = "B",
  "B-" = "B-",
  "C+" = "C+",
  "C" = "C",
  "C-" = "C-",
  "D+" = "D+",
  "D" = "D",
  "E (Failed)" = "E (Failed)",
}
